language: php
php:
  - 5.2
  - 5.3.2
  - 5.4

env:
  - DB=mysql
  - DB=postgres

before_script:
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash

script:
  - phpunit

notifications:
  email:
    recipients:
      - paul999@phpbb.com
    on_success: change
    on_failure: change
