language: php
php:
  - 5.2
  - 5.3.2
  - 5.4

before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.2' ]; then pear install --force phpunit/DbUnit; else pyrus install --force phpunit/DbUnit; fi"
  - phpenv rehash

script:
  - phpunit

notifications:
  email:
    recipients:
      - paul999@phpbb.com
    on_success: change
    on_failure: change
